name: run tweet.py

on:
  schedule:
    # - cron: '0 */4 * * *' # Every 4 hours
    - cron: '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run tweet.py
        env:
          NLTK_DATA: ${{ secrets.NLTK_DATA }}
          REDDIT_CLIENT: ${{ secrets.REDDIT_CLIENT }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          TWITTER_KEY: ${{ secrets.TWITTER_KEY }}
          TWITTER_KEY_SECRET: ${{ secrets.TWITTER_KEY_SECRET }}
          TWITTER_TOKEN: ${{ secrets.TWITTER_TOKEN }}
          TWITTER_TOKEN_SECRET: ${{ secrets.TWITTER_TOKEN_SECRET }}
        run: python tweet.py